name: Molecule
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        scenario:
#          - centos-8
#          - debian-10
#          - fedora-34
#          - oraclelinux-8
#          - ubuntu-20.04
    
    steps:
    - name: Setup Molecule
      uses: bec-galaxy/setup-molecule@v1
      
    - name: ls
      run: ls

    - name: Run Molecule tests
      working-directory: ../roles/development-env-go
      run: molecule test
 #     - name: Checkout
 #       uses: actions/checkout@v3
 #       with:
 #         path: "${{ github.repository }}"
 #     - name: Molecule
 #       uses: gofrolist/molecule-action@v2
 #       with:
 #         molecule_working_dir: "${{ github.repository }} /roles/development-env-go"
 #         molecule_options: --debug --base-config molecule/_shared/base.yml
 #         molecule_command: test
 #         molecule_args: --scenario-name ${{ matrix.scenario }}
 #       env:
 #         ANSIBLE_FORCE_COLOR: '1'
      
